[workspace]
resolver = "2"

members = ["problem-*"]

[workspace.dependencies]
itertools = "0.12"
rayon = "1.10"
anyhow = "1.0"
glam = "0.27"
tracing = "0.1.40"
tracing-subscriber = "0.3"
rstest = "0.18"
rstest_reuse = "0.6"
criterion = {version = "0.5", features = ["html_reports"]}
